// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdcV9cZf72ByU3IkD9zmzOIQe2OmvmagY',
    appId: '1:849194795711:web:3b79f59a8407b61c14fc0a',
    messagingSenderId: '849194795711',
    projectId: 'mostore-96b89',
    authDomain: 'mostore-96b89.firebaseapp.com',
    storageBucket: 'mostore-96b89.firebasestorage.app',
    measurementId: 'G-656C0Z400N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEuu7KbeCH6IQsCZuMWBhqjKoiAaFJ4xE',
    appId: '1:849194795711:android:0ec7a463f44b523a14fc0a',
    messagingSenderId: '849194795711',
    projectId: 'mostore-96b89',
    storageBucket: 'mostore-96b89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzxNWmV-q4BDFj-YoUSKvpMEeGwJR2A2s',
    appId: '1:849194795711:ios:4ad92e82d4c9a62d14fc0a',
    messagingSenderId: '849194795711',
    projectId: 'mostore-96b89',
    storageBucket: 'mostore-96b89.firebasestorage.app',
    iosBundleId: 'com.example.homework2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzxNWmV-q4BDFj-YoUSKvpMEeGwJR2A2s',
    appId: '1:849194795711:ios:4ad92e82d4c9a62d14fc0a',
    messagingSenderId: '849194795711',
    projectId: 'mostore-96b89',
    storageBucket: 'mostore-96b89.firebasestorage.app',
    iosBundleId: 'com.example.homework2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdcV9cZf72ByU3IkD9zmzOIQe2OmvmagY',
    appId: '1:849194795711:web:d6fab618e390c0bb14fc0a',
    messagingSenderId: '849194795711',
    projectId: 'mostore-96b89',
    authDomain: 'mostore-96b89.firebaseapp.com',
    storageBucket: 'mostore-96b89.firebasestorage.app',
    measurementId: 'G-G2JJDV9KB2',
  );
}
